classRoomVR/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth import views as auth_views
from ietimoodle.views import *
from rest_framework import routers, serializers, viewsets
from rest_framework.authtoken.models import Token


urlpatterns = [
     path('',include('ietimoodle.urls')),
     path('admin/', admin.site.urls),
     path('auth', include('ietimoodle.urls')),
     path('login/', LoginView.as_view(), name='login'),
     path('accounts/', include('django.contrib.auth.urls')), # new

]

ietimoodle/urls.py
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework.authtoken import views as apiviews
from rest_framework.authentication import TokenAuthentication, BasicAuthentication, SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework import routers
from rest_framework import routers, serializers, viewsets
from .models import *
from .serializers import *
from django.core import serializers
import json 
from . import api

app_name='moodle'   

urlpatterns = [
    path('', views.home, name='home'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('archivos/<str:element>/<str:filename>', views.download, name='download'),
    path('grade/<int:cursoid>', views.grade, name='grade'),
    path('qualifications/<int:cursoid>', views.qualifications, name='qualifications'),
    path('resource/<int:resourceid>', views.resource, name='resource'),
    path('task/<int:taskid>', views.task, name='task'),
    path('vrtask/<int:taskid>', views.vrtask, name='vrtask'),
    path('ad/<int:taskid>', views.addDelivery, name='addDelivery'),
    path('advr/<int:taskid>', views.addDeliveryVr, name='addDeliveryVr'),
    path('fc/<int:taskid>', views.fastCorrection, name='fastCorrection'),
    path('vr/fc/<int:taskid>', views.fastCorrectionVr, name='fastCorrectionVr'),
    path('<int:taskid>/<int:alumnid>', views.delivery, name='delivery'),
    path('vr/<int:taskid>/<int:alumnid>', views.vrdelivery, name='vrdelivery'),
    path('api/login',api.login),
    path('api/logout',api.logout),
    path('api/get_courses',api.get_courses),
    path('api/get_course_details',api.get_course_details),
    path('api/pin_request',api.pin_request),
    path('api/start_vr_exercise',api.start_vr_exercise), 
    path('api/finish_vr_exercise',api.finish_vr_exercise),
    path('actualizar/<int:qualificationID>/<int:nota>/<str:comentarioProfesor>',views.actualizarEjercicioIndiviual, name="actualizarEjercicio"),
    path('actualizar/vr/<int:qualificationID>/<int:nota>/<str:comentarioProfesor>',views.actualizarEjercicioIndiviualVR, name="actualizarEjercicioVR"),
    path('actualizar/<int:entrega>/<int:nota>/<str:comentarioProfesor>',views.actualizar, name="actualizar"),

]

urlpatterns += staticfiles_urlpatterns()

ietimoodle/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
# from .models import CustomUser

# class CustomUserCreationForm(UserCreationForm):

#     class Meta:
#         model = CustomUser
#         fields = ('username', 'email')

# class CustomUserChangeForm(UserChangeForm):

#     class Meta:
#         model = CustomUser
#         fields = ('username', 'email')
        
class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Correo', widget=forms.TextInput(attrs={'class': 'mb-4 mt-4 ml-[1.4%]'}))
    password = forms.CharField(label='Contraseña', widget=forms.TextInput(attrs={'type': 'password'}))
# myfield = forms.CharField(widget=forms.TextInput(attrs={'class': 'myfieldclass'}))

ietimoodle/views.py
import re
from django.shortcuts import render,  get_object_or_404, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
from django.http import HttpResponse, HttpResponseNotFound
from .forms import LoginForm
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.http import JsonResponse

from .models import *
from .serializers import * 
from rest_framework import viewsets
from django.contrib.auth.models import Permission
from rest_framework import permissions
import os, mimetypes


class MyAuthForm(AuthenticationForm):
	error_messages = {
		'invalid_login': _(
			"Asegurate de introducir el correo y la contraseña correctamente."
			" Ten en cuenta las máyusculas."
		),
		'inactive': _("El ususario no esta activo"),
	}


class LoginView(auth_views.LoginView):
	form_class = LoginForm
	authentication_form = MyAuthForm
	template_name = 'registration/login.html'

def home(request):
	return render(request, 'home.html')

def logout_view(request):
	logout(request)
	return render(request, "logout.html")

@login_required
def download(request, element, filename=''):
	if filename != '':
		try:
			BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
			filepath = BASE_DIR + '/archivos/' + element + '/' + filename
			path = open(filepath, 'rb')
			mime_type, _ = mimetypes.guess_type(filepath)
			response = HttpResponse(path, content_type=mime_type)
			response['Content-Disposition'] = "attachment; filename=%s" % filename
			return response
		except FileNotFoundError:
			return HttpResponseNotFound('Error 404 File not found')
	else:
		return render(request, 'file.html')

@login_required
def dashboard(request):
	suscripciones=Suscripcion.objects.filter(user=request.user.pk)
	cursos=Curso.objects.all
	content={
		'suscripciones': suscripciones,
		'cursos':cursos,
	}
	return render(request, 'dashboard.html', content)

@login_required
def grade(request, cursoid):
	recursos = Recurso.objects.filter(curso=cursoid)
	tareas = Tarea.objects.filter(curso=cursoid)
	vrtareas = VRTarea.objects.filter(curso=cursoid)
	role= Suscripcion.objects.filter(curso=cursoid, user=request.user.pk)[0]
	alumnos= Suscripcion.objects.filter(curso=cursoid,tipo='alumno')[0]
	firstAlId=get_object_or_404(User, pk=alumnos.user.pk)
	content= {
		'resources': recursos,
		'tasks': tareas,
		'vrtasks': vrtareas,
		'role': role,
		'grade': get_object_or_404(Curso, pk=cursoid),
		'firstal': firstAlId
	}
	return render(request, 'grade.html', content)

@login_required
def qualifications(request, cursoid):
	alumn=get_object_or_404(User, pk=request.user.pk)
	tasks = Tarea.objects.filter(curso=cursoid)
	vrtasks = VRTarea.objects.filter(curso=cursoid)
	deliveries=Entrega.objects.filter(user=alumn.pk, curso=cursoid)
	qualifications=[]
	for t in tasks:
		try:
			qualifications.append(Calificacion.objects.filter(user=alumn.pk, tarea=t.pk))
		except:
			continue
	vrqualifications=[]
	for vrt in vrtasks:
		try:
			vrqualifications.append(VRCalificacion.objects.filter(user=alumn.pk, vrtarea=vrt.pk))
		except:
			continue
	deliveriesRealizadas=[]
	deliveriesVRRealizadas=[]
	for d in deliveries:
		try:
			deliveriesRealizadas.append(d.tarea.pk)
		except:
			continue
	for d in deliveries:
		try:
			deliveriesVRRealizadas.append(d.vrtarea.pk)
		except:
			continue
	content= {
		'grade': get_object_or_404(Curso, pk=cursoid),
		'alumn': alumn,
		'tasks': tasks,
		'vrtasks': vrtasks,
		'deliveries': deliveries,
		'qualifications': qualifications,
		'vrqualifications': vrqualifications,
		'deliveriesRealizadas': deliveriesRealizadas,
		'deliveriesVRRealizadas': deliveriesVRRealizadas,
	}
	return render(request, 'qualifications.html', content)

@login_required
def resource(request, resourceid):
	resource=get_object_or_404(Recurso, pk=resourceid)
	curso=get_object_or_404(Curso, pk=resource.curso.pk)
	content= {
		'resource': resource,
		'curso': curso
	}
	return render(request, 'resource.html', content)

@login_required
def task(request, taskid):
	task=get_object_or_404(Tarea, pk=taskid)
	curso=get_object_or_404(Curso, pk=task.curso.pk)
	alumn=get_object_or_404(User, pk=request.user.pk)
	qualification=Calificacion.objects.filter(user=alumn.pk, tarea=task.pk)
	tasks=Tarea.objects.filter(curso=curso.pk)
	vrtasks=VRTarea.objects.filter(curso=curso.pk)
	entrega=Entrega.objects.filter(tarea=taskid, user=alumn.pk)
	content= {
		'task': task,
		'curso': curso,
		'entrega': entrega,
		'qualification': qualification,
		'tasks': tasks,
		'vrtasks': vrtasks
	}
	return render(request, 'task.html', content)

@login_required
def vrtask(request, taskid):
	task=get_object_or_404(VRTarea, pk=taskid)
	curso=get_object_or_404(Curso, pk=task.curso.pk)
	alumn=get_object_or_404(User, pk=request.user.pk)
	qualification=VRCalificacion.objects.filter(user=alumn.pk, vrtarea=task.pk)
	tasks=Tarea.objects.filter(curso=curso.pk)
	vrtasks=VRTarea.objects.filter(curso=curso.pk)
	entrega=Entrega.objects.filter(vrtarea=taskid, user=alumn.pk)
	content= {
		'task': task,
		'curso': curso,
		'entrega': entrega,
		'qualification': qualification,
		'tasks': tasks,
		'vrtasks': vrtasks,
	}
	return render(request, 'vrtask.html', content)

@login_required
def addDelivery(request, taskid):
	task=get_object_or_404(Tarea, pk=taskid)
	grade=get_object_or_404(Curso, pk=task.curso.pk)
	user=get_object_or_404(User, pk=request.user.pk)
	tasks=Tarea.objects.filter(curso=grade.pk)
	curso=get_object_or_404(Curso, pk=task.curso.pk)
	vrtasks=VRTarea.objects.filter(curso=curso.pk)
	delivery=Entrega.objects.filter(tarea=taskid, user=user.pk)
	content= {
		'task': task,
		'grade': grade,
		'delivery': delivery,
		'tasks': tasks,
		'vrtasks': vrtasks,
		'vr': False
	}
	return render(request, 'addDelivery.html', content)

@login_required
def addDeliveryVr(request, taskid):
	task=get_object_or_404(VRTarea, pk=taskid)
	grade=get_object_or_404(Curso, pk=task.curso.pk)
	user=get_object_or_404(User, pk=request.user.pk)
	tasks=Tarea.objects.filter(curso=grade.pk)
	curso=get_object_or_404(Curso, pk=task.curso.pk)
	vrtasks=VRTarea.objects.filter(curso=curso.pk)
	delivery=Entrega.objects.filter(vrtarea=taskid, user=user.pk)
	content= {
		'task': task,
		'grade': grade,
		'delivery': delivery,
		'tasks': tasks,
		'vrtasks': vrtasks,
		'vr': True
	}
	return render(request, 'addDelivery.html', content)

@login_required
def delivery(request, taskid, alumnid):
	alumn= get_object_or_404(User, pk=alumnid)
	task=get_object_or_404(Tarea, pk=taskid)
	curso=get_object_or_404(Curso, nombre=task.curso)
	vr = False

	try:
		deliveries=Entrega.objects.filter(tarea=taskid, user=alumnid)
		alumnos= Suscripcion.objects.filter(curso=curso.pk, tipo="alumno")
		qualification=Calificacion.objects.filter(tarea=taskid, user=alumnid)
		alumnosCurso = []
		for a in alumnos:
			alumnosCurso.append(a.user.pk)
		if alumnosCurso.index(alumnid) == len(alumnosCurso)-1:
			nextAlumn=alumnosCurso[0]
		else:
			nextAlumn=alumnosCurso[alumnosCurso.index(alumnid)+1]
		
		if alumnosCurso.index(alumnid) == 0:
			prevAlumn=alumnosCurso[-1]
		else:
			prevAlumn=alumnosCurso[alumnosCurso.index(alumnid)-1]
	except:
		deliveries=""
		prevAlumn=""
		nextAlumn=""
	
	
	content = {
		'alumn': alumn,
		'task': task,
		'deliveries': deliveries,
		'nextAlumn': nextAlumn,
		'prevAlumn': prevAlumn,
		'qualification': qualification,
		'curso': curso,
		'vr': vr,
	}
	return render(request, 'delivery.html', content)

@login_required
def vrdelivery(request, taskid, alumnid):
	alumn= get_object_or_404(User, pk=alumnid)
	task=get_object_or_404(VRTarea, pk=taskid)
	curso=get_object_or_404(Curso, nombre=task.curso)
	try:
		deliveries=Entrega.objects.filter(vrtarea=taskid, user=alumnid)
		alumnos= Suscripcion.objects.filter(curso=curso.pk, tipo="alumno")
		qualification=VRCalificacion.objects.filter(vrtarea=taskid, user=alumnid)
		alumnosCurso = []
		for a in alumnos:
			alumnosCurso.append(a.user.pk)
		if alumnosCurso.index(alumnid) == len(alumnosCurso)-1:
			nextAlumn=alumnosCurso[0]
		else:
			nextAlumn=alumnosCurso[alumnosCurso.index(alumnid)+1]
		
		if alumnosCurso.index(alumnid) == 0:
			prevAlumn=alumnosCurso[-1]
		else:
			prevAlumn=alumnosCurso[alumnosCurso.index(alumnid)-1]
	except:
		deliveries=""
		prevAlumn=""
		nextAlumn=""
	
	
	content = {
		'alumn': alumn,
		'task': task,
		'deliveries': deliveries,
		'nextAlumn': nextAlumn,
		'prevAlumn': prevAlumn,
		'qualification': qualification,
		'curso': curso,
	}
	return render(request, 'delivery.html', content)

@login_required
def fastCorrection(request, taskid):
	task=get_object_or_404(Tarea, pk=taskid)
	curso=get_object_or_404(Curso, nombre=task.curso)
	deliveries=Entrega.objects.filter(tarea=task.pk)
	alumnos= Suscripcion.objects.filter(curso=curso.pk, tipo="alumno")
	qualifications=Calificacion.objects.filter(tarea=task.pk)
	alumnosEntregado=[]
	vr=False
	for d in deliveries:
		alumnosEntregado.append(d.user.pk)
	
	content = {
		'alumnos': alumnos,
		'task': task,
		'deliveries': deliveries,
		'alumnosEntregado': alumnosEntregado,
		'qualifications': qualifications,
		'curso': curso,
		'vr':vr,
	}
	return render(request, 'fastCorrection.html', content)

@login_required
def fastCorrectionVr(request, taskid):
	task=get_object_or_404(VRTarea, pk=taskid)
	curso=get_object_or_404(Curso, nombre=task.curso)
	deliveries=Entrega.objects.filter(vrtarea=task.pk)
	alumnos= Suscripcion.objects.filter(curso=curso.pk, tipo="alumno")
	curso=get_object_or_404(Curso, pk=task.curso.pk)
	qualifications=VRCalificacion.objects.filter(vrtarea=taskid)
	alumnosEntregado=[]
	vr=True
	for d in deliveries:
		alumnosEntregado.append(d.user.pk)
	
	content = {
		'alumnos': alumnos,
		'task': task,
		'deliveries': deliveries,
		'alumnosEntregado': alumnosEntregado,

ietimoodle/templates/addDelivery.html
<html>
    {% include "header.html" with title="Deliver" vr=vr taskid=task.pk task=task.nombre curso=grade%}
    <h2 class="pt-5 pl-20 text-4xl">{{grade.nombre}} / {{task.nombre}}</h2>
    <div id="exercise" class="pl-20 pr-20 pt-5 ">
        <div class="flex">
            <div id="previewExercises" class="min-w-[25%] max-w-[25%]">
                <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 mb-3">
                    <ul>
                        <li><p class="font-bold text-lg">Tareas de {{grade.nombre}}:</p>
                            <ul class="pl-8">
                                {% for t in tasks %}
                                    {% if t.visibilidad == True%}
                                        <li>
                                            • <a class="text-base underline text-[#461f87]" href="../task/{{t.pk}}">{{t.nombre}}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% for t in vrtasks %}
                                    {% if t.visibilidad == True%}
                                        <li>
                                            • <a class="text-base underline text-[#461f87]" href="../vrtask/{{t.pk}}">{{t}}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="addFile" class="min-w-[75%] max-w-[75%]">
                {% if delivery.0 %}
                    <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 mb-3">
                        <table id="fctable" class="min-w-full">
                            <tr class="text-center font-bold">
                                <td><p>Número de entrega</p></td>
                                <td><p>Fecha de entrega</p></td>
                                <td><p>Archivo entregado</p></td>
                            </tr>
                            {% for d in delivery %}
                                <tr class="text-center">
                                    <td>
                                        <p class="italic">Entrega {{forloop.counter}}</p>
                                    </td>
                                    <td>
                                        <p>{{d.fecha_entrega}}</p>
                                    </td>
                                    <td>
                                        <a class="italic underline text-[#461f87]" href="../../{{d.archivo}}">Descargar</a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="3">
                                        <p>• No hay entregas realizadas en esta tarea.</p>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                {% else %}
                        <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 mb-3 flex">
                            {% load static %}
                            <img class="max-w-[30px] max-h-[30px] ml-3 mr-8" src="{% static 'warning.png' %}" alt="Warning"><p class="text-xl">No hay entregas realizadas en esta tarea</p>
                        </div>
                {% endif %}
                <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 mb-3 flex">
                    <p class="font-bold pr-5">Realiza tu entrega: </p>
                    <input type="file">
                </div>
            </div>
        </div>
    </div>
</body>
</html>

ietimoodle/templates/dashboard.html
<html>
    {% include "header.html" with title="Dashboard" %}
        <h2 class="pt-5 pl-20 text-4xl">Cursos de {{user.username}}:</h2>
        <div class="p-20 pt-5">
        {% for s in suscripciones %}
            <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 ">
                <a class="text-3xl underline text-[#461f87]" href="../grade/{{s.curso.pk}}">{{s.curso}}</a> 
                {% for i in cursos %}
                    {% if i.nombre|stringformat:"s" == s.curso|stringformat:"s" %}
                    <p class="italic">{{ i.descripcion }}</p>
                    {% endif %}
                {% endfor %}
                <p class="text-lg">Rol asignado: {{s.tipo}}</p>
            </div>
        {% endfor %}
        </div>
    </body>
</html>

ietimoodle/templates/grade.html
<html>
    {% include "header.html" with title="Curso" curso=grade %}
    <h2 class="pt-5 pl-20 text-4xl">Recursos de {{grade}}</h2>
    <div id="recursos" class="pl-20 pr-20 pt-5">
        {% for r in resources %}
            <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 mb-3">
                <a class="text-2xl underline text-[#461f87]" href="../resource/{{r.pk}}">{{r}}</a>
                <p class="pl-10 italic">Vista general: {{r.texto}}</p>
                {% if r.archivo %}
                    <p class="pl-10 italic underline">1 fichero adjunto</p>
                {% else %}
                    <p class="pl-10 italic underline">*No hay ficheros adjuntos</p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <div id="tituloTareas" class="flex">
        <h2 class="pt-2 pl-20 text-4xl">Tareas de {{grade}}</h2>
        {% if role.tipo == "alumno" %}
            <button class="p-1 mt-2 ml-10 font-bold"><a href="../qualifications/{{grade.pk}}">Cualificaciones de {{grade.nombre}}</a></button>
        {% endif %}
    </div>
    <div id="tareas" class="pl-20 pr-20 pt-5">
        {% if tasks %}
            {% for t in tasks %}
                {% if t.visibilidad == True or role.tipo == "profesor" %}
                    {% if role.tipo == "profesor"  and t.visibilidad == False %} 
                        {% load static %}
                        <p class="pl-10 italic flex"><img class="max-w-[18px] max-h-[18px]" src="{% static 'warning.png' %}" alt="Warning">Tarea oculto para el alumnado</p>
                    {% endif %}
                    <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 mb-3">
                        {% if role.tipo == "profesor" %}
                            <a class="text-2xl underline text-[#461f87]" href="../{{t.pk}}/{{firstal.pk}}">{{t}}</a>
                        {% else %}
                            <a class="text-2xl underline text-[#461f87]" href="../task/{{t.pk}}">{{t}}</a>
                        {% endif %}
                        <p class="pl-10 italic">Ponderación: {{t.ponderacion}}</p>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if vrtasks %}
            {% for t in vrtasks %}
                {% if t.visibilidad == True or role.tipo == "profesor" %}
                    {% if role.tipo == "profesor"  and t.visibilidad == False %} 
                        {% load static %}
                        <p class="pl-10 italic flex"><img class="max-w-[18px] max-h-[18px]" src="{% static 'warning.png' %}" alt="Warning">Tarea oculto para el alumnado</p>
                    {% endif %}
                    <div class="border-solid rounded border-black bg-[#ededed] p-2 mx-8 mb-3">
                        {% if role.tipo == "profesor" %}
                            <a class="text-2xl underline text-[#461f87]" href="../vr/{{t.pk}}/{{firstal.pk}}">{{t}}</a>
                        {% else %}
                            <a class="text-2xl underline text-[#461f87]" href="../vrtask/{{t.pk}}">{{t}}</a>
                        {% endif %}
                        <p class="pl-10 italic">Ponderación: {{t.ponderacion}}</p>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    </body>
</html>

ietimoodle/templates/header.html
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-84RC3PPX48"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-84RC3PPX48');
    </script>
    <meta name="google-site-verification" content="QlJijYk74BBBPfM_iigsTVLrtRkGftCMeYdJtPrAypU" />
    {% if title == "Curso" %}
        <title>{{curso}}</title>
    {% elif title == "Resource" %}
        <title>{{resource}}</title>
    {% elif title == "Task" %}
        <title>{{task}}</title>
    {% elif title == "Delivery" %}
        <title>{{task}}</title>
    {% elif title == "Qualifications" %}
        <title>Cualificaciones de {{curso.nombre}}</title>
    {% elif title == "Deliver" %}
        <title>Añadir entrega a {{task}}</title>
    {% else %}
        <title>{{title}}</title>
    {% endif %}
    <script src="https://cdn.tailwindcss.com"></script>
    {% load static %}
    <!-- import fuente Roboto -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <!-- import funete Assistant -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@500&family=Roboto:wght@300&display=swap" rel="stylesheet">

    <script
        src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
    <script src="{% static 'funciones.js' %}"></script>
    
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="pt-5 pb-0 pr-10 pl-10 flex justify-between">
        <div>
        <a href=".."><img class="w-20" src="{% static 'logo.png' %}" alt="WLYLogo"></a>
        {% if title == "Home" %}
        <a class="underline text-[#461f87]" href="">Home</a>
        {% elif title == "Dashboard" %}
        <a class="underline text-[#461f87]" href="..">Home</a> / 
        <a class="underline text-[#461f87]" href="">Cursos</a>
        {% elif title == "Delivery" or title == "Fast Correction" %}
        <a class="underline text-[#461f87]" href="../../">Home</a> / 
        <a class="underline text-[#461f87]" href="../../dashboard">Cursos</a> /
        <a class="underline text-[#461f87]" href="../../grade/{{cursoid}}">{{curso}}</a> / 
        <a class="underline text-[#461f87]" href="">{{task}}</a>
        {% elif title == "Curso" %}
        <a class="underline text-[#461f87]" href="../..">Home</a> / 
        <a class="underline text-[#461f87]" href="../dashboard">Cursos</a> / 
        <a class="underline text-[#461f87]" href="">{{curso}}</a>
        {% elif title == "Resource" %}
        <a class="underline text-[#461f87]" href="..">Home</a> / 
        <a class="underline text-[#461f87]" href="../dashboard">Cursos</a> / 
        <a class="underline text-[#461f87]" href="../grade/{{cursoid}}">{{curso}}</a> / 
        <a class="underline text-[#461f87]" href="">{{resource}}</a>
        {% elif title == "Task" %}
        <a class="underline text-[#461f87]" href="..">Home</a> / 
        <a class="underline text-[#461f87]" href="../dashboard">Cursos</a> /
        <a class="underline text-[#461f87]" href="../grade/{{cursoid}}">{{curso}}</a> / 
        <a class="underline text-[#461f87]" href="">{{task}}</a>
        {% elif title == "Qualifications" %}
        <a class="underline text-[#461f87]" href="..">Home</a> / 
        <a class="underline text-[#461f87]" href="../dashboard">Cursos</a> /
        <a class="underline text-[#461f87]" href="../grade/{{curso.pk}}">{{curso.nombre}}</a> / 
        <a class="underline text-[#461f87]" href="">Cualificaciones de {{curso.nombre}}</a>
        {% elif title == "Deliver" %}
        <a class="underline text-[#461f87]" href="..">Home</a> / 
        <a class="underline text-[#461f87]" href="../dashboard">Cursos</a> /
        <a class="underline text-[#461f87]" href="../grade/{{curso.pk}}">{{curso.nombre}}</a> / 
        {% if vr %}
            <a class="underline text-[#461f87]" href="../vrtask/{{taskid}}">{{task}}</a> /
        {% else %}
            <a class="underline text-[#461f87]" href="../task/{{taskid}}">{{task}}</a> /  
        {% endif %}
        <a class="underline text-[#461f87]" href="">Añadir entrega a {{task}}</a>
        {% endif %}
        </div>
        <div>
            <p class="text-right">{{user.username}}</p>
            {% if request.user.is_authenticated %}
                <a class="underline text-[#461f87]" href="{% url 'moodle:logout' %}"><p class="text-right">Logout</p></a>
            {% endif %}
        </div>
    </header>

ietimoodle/templates/home.html
<html>
    {% include "header.html" with title="Home" %}
    <div class="p-20 max-w-2xl max-h-2xl flex flex-col items-center align-center m-auto">
        {% load static %}
        <img src="{% static 'logo.png' %}" alt="WLYLogo">
        <div>
            {% if not request.user.is_authenticated %}
                <button class="rounded-lg p-2 bg-[#461f87] text-[#ededed]" onclick="location.href='login'">Log In</button>
            {% else %}
                <button class="rounded-lg p-2 bg-[#461f87] text-[#ededed]" onclick="location.href='dashboard'">Dashboard</button>
            {% endif %}
        </div>
    </div>
    </body>
</html>